# Generated by Django 4.1.3 on 2022-11-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='articles',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='tags',
            new_name='tag',
        ),
    ]
